import { CapabilityRegistry, type PublicCapability } from "../../framework/capabilities/capabilityRegistry.js";

const ECHO_CAPABILITIES: readonly PublicCapability[] = [
  {
    id: "choir_knowledge",
    title: "Choir information",
    summary: "Answer questions using current rota, attendance, event, member, song, resource and indexed-document evidence.",
    kind: "knowledge",
    minimumRole: "member",
    examples: ["What is the schedule for this week?", "Who was unavailable yesterday?"],
    notes: ["Echo retrieves current evidence and does not invent missing records."],
    helpText: "Answering choir, rota, attendance, song, event, and resource questions.",
  },
  {
    id: "quoted_conversation",
    title: "Quoted-message conversation",
    summary: "Understand a quoted message alongside the current question in casual, retrieval and workflow conversations.",
    kind: "conversation",
    minimumRole: "member",
    examples: ["Reply to a message and ask Echo to explain it."],
    helpText: "Replying with quoted-message context when you quote or reply to a message.",
  },
  {
    id: "member_memory",
    title: "Member memory",
    summary: "Learn bounded, useful and non-sensitive member preferences for conversational continuity.",
    kind: "conversation",
    minimumRole: "member",
    examples: ["Remember that I prefer morning rehearsal reminders."],
    notes: ["Sensitive personal data is not stored as conversational memory."],
    helpText: "Learning useful, non-sensitive member preferences over time.",
  },
  {
    id: "member_mentions",
    title: "Member mentions",
    summary: "Resolve known choir members and prepare messages that mention them through the active transport.",
    kind: "conversation",
    minimumRole: "member",
    examples: ["Tag me and say rehearsal starts at 5pm."],
    helpText: "Tagging known choir members when a message requires it.",
  },
  {
    id: "one_time_reminders",
    title: "One-time reminders",
    summary: "Create, edit and cancel one-time reminders with deterministic date handling and owner confirmation.",
    kind: "workflow",
    minimumRole: "member",
    examples: ["@Echo remind me next Thursday about rehearsal.", "Reply to a message with @Echo remind me tomorrow."],
    notes: ["Creation, edits and cancellation require confirmation through the reminder reply chain."],
    helpText: "Creating, editing, and cancelling confirmed one-time reminders.",
  },
  {
    id: "recurring_agent_tasks",
    title: "Recurring reminders",
    summary: "Schedule a reusable objective that retrieves fresh information and runs daily, weekly or monthly.",
    kind: "workflow",
    minimumRole: "superuser",
    examples: ["Echo, remind me every Monday at 6pm to send an attendance report."],
    notes: ["The first real result is sent immediately.", "Only the owner can list, update, pause, resume or cancel the task."],
    helpText: "Creating and managing recurring agent reminders with `remind`.",
  },
  {
    id: "setlist_submission",
    title: "Setlist submission",
    summary: "Submit or correct combined, worship-only or praise-only setlists for the appropriate service week.",
    kind: "workflow",
    minimumRole: "member",
    examples: ["Post the songs with #submit_setlist."],
    notes: ["The backend validates the assigned leader and service week."],
    helpText: "Submitting or correcting setlists with `#submit_setlist`.",
  },
  {
    id: "automatic_choir_operations",
    title: "Automatic choir operations",
    summary: "Evaluate weekly rota reminders, setlist follow-ups, broadcasts and cleanup when the scheduler activates them.",
    kind: "automatic",
    minimumRole: "member",
    examples: [],
    notes: ["Echo checks current evidence before deciding whether a message should be sent."],
    helpText: "Sending applicable rota and setlist messages automatically.",
  },
  {
    id: "schedule_visibility",
    title: "Schedule visibility",
    summary: "List active scheduled messages and their readable next execution times.",
    kind: "administration",
    minimumRole: "superuser",
    examples: ["schedules"],
    helpText: "Viewing scheduled messages with `schedules`.",
  },
  {
    id: "knowledge_sync",
    title: "Knowledge synchronization",
    summary: "Explicitly synchronize configured choir knowledge sources without stopping Echo when synchronization fails.",
    kind: "administration",
    minimumRole: "superuser",
    examples: ["sync"],
    helpText: "Synchronizing choir knowledge with `sync`.",
  },
  {
    id: "member_administration",
    title: "Member administration",
    summary: "Add or correct private member identifiers and canonical choir names through audited, confirmed tools.",
    kind: "administration",
    minimumRole: "creator",
    examples: ["Add this verified phone number to a member."],
    notes: ["Sensitive changes require creator confirmation."],
    helpText: "Managing verified member identities with confirmation.",
  },
  {
    id: "scheduler_controls",
    title: "Scheduler controls",
    summary: "Deactivate all scheduled messages or reactivate and rebuild the appropriate schedules.",
    kind: "administration",
    minimumRole: "creator",
    examples: ["scheduler deactivate", "scheduler activate"],
    helpText: "Activating or deactivating scheduled messages.",
  },
  {
    id: "application_clock",
    title: "Application clock",
    summary: "Inspect, mock, advance or restore Echo's centralized application time for controlled testing.",
    kind: "administration",
    minimumRole: "creator",
    examples: ["clock help", "clock set 2026-09-07 18:00", "clock advance 1 day", "clock clear"],
    notes: ["Clock control is restricted to the creator."],
    helpText: "Controlling test time with the creator-only `clock` commands.",
  },
  {
    id: "manual_sunday_reminder",
    title: "Manual Sunday reminder",
    summary: "Run the normal Sunday rota-reminder workflow immediately and deliver an applicable result to the choir group.",
    kind: "administration",
    minimumRole: "creator",
    examples: ["send sunday reminder"],
    notes: ["This command must be sent in the creator's private chat with Echo."],
    helpText: "Running the Sunday reminder manually from the creator's private chat.",
  },
];

export const echoCapabilityRegistry = new CapabilityRegistry(ECHO_CAPABILITIES);
